### PR TITLE
Added maps to allow multi-dof velocity publishing.

### PR DESCRIPTION
**Pull request by tonybaltovski**
This should allow the usage of all axes and it will not break backwards compatibility as discussed in PR #5.  Mike, mentioned hash maps which I believe are unordered maps in C++.  They don't seem to be supported very widely since they new in C++11.  Any thoughts on this?

### CODE REVIEW

**Comment by 130s** [comment]
@tonybaltovski Do you have any working example of how to set up the map? If not I'll just try decoding but if you have one that would help a lot. Thanks.

**Comment by 130s** [comment]
Without changing anything I was just able to run this for diff-drive teleop with PS3 joystick. The behavior doesn't seem to change. So +1.

I'm afraid this PR might not work out of the box for linear move in y-direction, which is what I wanted in #7. Once this PR is merged maybe I'll open another PR for achieving that.

**Comment by tonybaltovski** [comment]
@130s you need to add something like this to your config yaml:

```
  teleop_twist_joy:
    axis_linear:
      x: 1
      y: 2
    scale_linear:
      x: 0.4
      y: 0.4
    axis_angular: 0
    scale_angular: 1.4
```

**Comment by 130s** [comment]
@tonybaltovski thanks, I'll give it a try when I'll have an access to a device next time.

@mikepurvis is there anything that keeps reviewers on hold for this?

**Comment by mikepurvis** [comment]
@130s I just haven't had a chance to test it manually, and the repo doesn't have automatic tests. If you assert that it works for you, I'm happy to merge on that basis.

**Comment by mikepurvis** [comment]
LGTM

**Pull request merged**
