### PR TITLE
Added 3D twist publishing.

### PR DESCRIPTION
**Pull request by tonybaltovski**
Not sure if this is any of use but I was using this for sending a 3D twist to a quad-rotor so I thought I'd open a PR.

### CODE REVIEW

**Comment by mikepurvis** [comment]
I like this in principle, but I wish there was a way for it to be backward compatible— that existing teleop_twist_joy configs would break is a non-starter, but even apart from that, it's a bummer for planar systems to pay the configuration complexity cost of supporting 3D holonomic robots.

For example, instead of `axis_linear_x`, `axis_linear_y`, and `axis_linear_x`, what about just maintaining `axis_linear` and adding `axis_vertical` and `axis_strafe`? Similarly, the scale params could just be `scale_linear` (synonym `scale_horizonal`?) and `scale_vertical`.

Anyhow, not saying it has to be this way, just trying to brainstorm an interface that would be not-insane for the simple use case while also covering some basic quadrotor commands.

**Comment by tonybaltovski** [comment]
Maybe a new node/package all together would be better?  Aircraft use either velocities or angular rates so it would increase the complexity if the angular rates was added (which I planned to).  However, this could easily be extended to a planar holonomic robots.  Nice synonyms, strafing in particular.  I'll update this to be backwards compatible.

**Comment by mikepurvis** [comment]
Maybe the names are unnecessary indirection, though? Here's another thought:
- The axis_linear param can accept either a float or an hashmap specifying x, y, z members.
- If a float is specified, it's implied that that means the x component of the hashmap.

So for the differential drive case, the config is:

```
  teleop_twist_joy:
    axis_linear: 1
    scale_linear: 0.4
    axis_angular: 0
    scale_angular: 1.4
```

But for a mecanum or caster base, it's:

```
  teleop_twist_joy:
    axis_linear:
      x: 1
      y: 2
    scale_linear:
      x: 0.4
      y: 0.4
    axis_angular: 0
    scale_angular: 1.4
```

And similarly for a quadcopter, you simply add the z component to the map.

Again, there's a line here— for any robot of sufficient complexity, a bespoke teleop node will be required; the intent here is to provide basic and standard functionality for simple robots.

**Comment by tonybaltovski** [comment]
That does seem like a better idea, that would allow the user to select which axes that they need.  Indeed, there is that line but filling up a twist message from a joystick is pretty novel. I'll try to implement this with maps and get your thoughts on it.  I'll close this.

**Pull request closed without merging**
