### PR TITLE
Fix segfaults

### PR DESCRIPTION
**Pull request by clalancette**
The individual patches have more information, but this PR fixes a couple of different segfaults that could happen if the published Joy message contained less fields than teleop_twist_joy expected.

### CODE REVIEW

**Comment by clalancette** [comment]
The travis CI failure looks like infrastructure issues, unrelated to this PR.

**Comment by mikepurvis** [comment]
This all seems reasonable, and some nice cleanup. Much appreciated.

**Comment by vincentrou** [comment]
The code looks good to me and the tests are passing for me.
I will merge this.

**Comment by clalancette** [comment]
> The code looks good to me and the tests are passing for me.
> I will merge this.

Thank you!

**Pull request merged**
